### ISSUE TITLE
The column type for LocalDate with the hibernate data addon is generated incorrectly

### ISSUE THREAD

**Issue by TikhomirovME** [Haulmont/jmix-all#11]
**Reproducing the problem:**

1. Connect io.mix.data:jmix-hibernate-starter
2. Create a JPA Entity with an attribute of the LocalDate type
![изображение](https://user-images.githubusercontent.com/83810852/123587496-6e28e580-d7f7-11eb-937e-86ec511b8690.png)
3. Based on the entity, create an editing screen Backoffice -\> New -\> Screen
4. Launch the application, a preview of the generated liquibase scripts will open before launching
![изображение](https://user-images.githubusercontent.com/83810852/123587648-a2040b00-d7f7-11eb-99c6-0877fec8d3e4.png)
ER: The field type is equal to the TIME type
AR: The field type is equal to the DATETIME type

There is a similar problem with the LocalDate type, but this type does not cause a problem in runtime.

**Problem description:**

When generating changesets for liquibase, the _getJavaType method is called

com.haulmont.jpb.db.dll.AbstractLiquibaseGenerator#_getJavaType

Within it, there is an attempt to get a converter for the attribute.
![изображение](https://user-images.githubusercontent.com/83810852/123587935-1179fa80-d7f8-11eb-8a3e-468b03c00057.png)

If eclipselink is used, the system does not find the converter and returns null. If hibernate is used, the system finds a converter
https://docs.spring.io/spring-data/data-jpa/docs/current/api/org/springframework/data/jpa/convert/threeten/Jsr310JpaConverters.LocalTimeConverter.html
![изображение](https://user-images.githubusercontent.com/83810852/123588041-3b332180-d7f8-11eb-8f5a-325a06efa9a3.png)
![изображение](https://user-images.githubusercontent.com/83810852/123588066-4423f300-d7f8-11eb-9afc-aa7345f8bcdb.png)
![изображение](https://user-images.githubusercontent.com/83810852/123588094-500fb500-d7f8-11eb-9070-2e78d3c115ac.png)
Then, when using this converter in the com.haulmont.spb.db.dll.AbstractLiquibaseGenerator#getJavaType method, the java.util.Date type is returned
![изображение](https://user-images.githubusercontent.com/83810852/123588239-85b49e00-d7f8-11eb-91eb-56a2215d4824.png)
Based on it, the system generates the DATETIME field type in changeset

If eclipselink is used, the converter returns null and the Time type is returned in the com.haulmont.spb.db.dll.AbstractLiquibaseGenerator#getJavaType method.

If you make a stub for checking LocalDate and LocalTime, then script generation occurs in the same way as when using eclipselink.
![изображение](https://user-images.githubusercontent.com/83810852/123588330-a67cf380-d7f8-11eb-8812-e13182c24781.png)

**Comment by andreysubbotin** [comment]
Jmix framework doesn't support Hibernate.
